
import { Destination, TravelPackage, BlogPost, VisaType } from './types';

export const INITIAL_DESTINATIONS_DATA: Destination[] = [
  { id: 'portugal', name: 'Portugal', description: 'Praias ensolaradas e cidades históricas.', longDescription: 'Explore as charmosas ruas de Lisboa, os vinhedos do Porto e a deslumbrante costa do Algarve. Portugal oferece uma rica história, cultura vibrante e culinária deliciosa.', imageUrl: 'https://picsum.photos/seed/portugal/800/600', category: 'Europa', popular: true },
  { id: 'france', name: 'França', description: 'Marcos icônicos e culinária de classe mundial.', longDescription: 'Do encanto romântico de Paris e os campos de lavanda da Provence à glamourosa Riviera Francesa, a França cativa com sua arte, moda e gastronomia.', imageUrl: 'https://picsum.photos/seed/france/800/600', category: 'Europa', popular: true },
  { id: 'england', name: 'Inglaterra', description: 'História rica e uma cena cultural vibrante.', longDescription: 'Descubra os pontos turísticos icônicos de Londres, o charme histórico de Oxford e Cambridge e a pitoresca paisagem rural. A Inglaterra combina séculos de tradição com dinamismo moderno.', imageUrl: 'https://picsum.photos/seed/england/800/600', category: 'Europa', popular: true },
  { id: 'canada', name: 'Canadá', description: 'Paisagens de tirar o fôlego e cidades diversas.', longDescription: 'Experimente as majestosas Montanhas Rochosas, as cidades cosmopolitas de Toronto e Vancouver e a herança francesa única de Quebec. O Canadá oferece vasta natureza selvagem e centros urbanos acolhedores.', imageUrl: 'https://picsum.photos/seed/canada/800/600', category: 'América do Norte', popular: true },
  { id: 'japan', name: 'Japão', description: 'Tradições antigas e tecnologia futurista.', longDescription: 'Mergulhe na beleza serena dos templos de Kyoto, na energia vibrante de Tóquio e nas deslumbrantes paisagens naturais, das cerejeiras em flor às montanhas cobertas de neve.', imageUrl: 'https://picsum.photos/seed/japan/800/600', category: 'Ásia' },
  { id: 'italy', name: 'Itália', description: 'Arte, história e delícias culinárias.', longDescription: 'Viaje pelas ruínas antigas de Roma, a arte renascentista de Florença, os canais românticos de Veneza e a cênica Costa Amalfitana. A Itália é um banquete para os sentidos.', imageUrl: 'https://picsum.photos/seed/italy/800/600', category: 'Europa' },
];

export const INITIAL_PACKAGES_DATA: TravelPackage[] = [
  { id: 'pkg1', name: 'Explorador de Lisboa', destinationName: 'Portugal', price: 0, duration: '5 Dias / 4 Noites', itinerary: ['Chegada & Tour por Alfama', 'Torre de Belém & Jerónimos', 'Passeio de um dia a Sintra', 'Mercado & Noite de Fado', 'Partida'], imageUrl: 'https://picsum.photos/seed/lisbonpkg/600/400', details: 'Descubra o coração de Portugal com passeios guiados, experiências culturais e acomodação confortável.' },
  { id: 'pkg2', name: 'Sonhos Parisienses', destinationName: 'França', price: 0, duration: '4 Dias / 3 Noites', itinerary: ['Torre Eiffel & Cruzeiro no Sena', 'Visita ao Museu do Louvre', 'Montmartre & Sacré-Cœur', 'Passeio ao Palácio de Versalhes', 'Partida'], imageUrl: 'https://picsum.photos/seed/parispkg/600/400', details: 'Experimente a magia de Paris com visitas a marcos icônicos, museus de classe mundial e bairros charmosos.' },
  { id: 'pkg3', name: 'Chamada de Londres', destinationName: 'Inglaterra', price: 0, duration: '5 Dias / 4 Noites', itinerary: ['Chegada & Visão Geral da Cidade', 'Palácio de Buckingham & Westminster', 'Museu Britânico & Torre de Londres', 'Passeio de um dia a Stonehenge & Bath', 'Partida'], imageUrl: 'https://picsum.photos/seed/londonpkg/600/400', details: 'Explore a histórica Londres e seus arredores, mergulhando na história real e mistérios antigos.'},
  { id: 'pkg4', name: 'Aventura nas Rochosas Canadenses', destinationName: 'Canadá', price: 0, duration: '7 Dias / 6 Noites', itinerary: ['Chegada em Calgary, Transfer para Banff', 'Lago Louise & Lago Moraine', 'Passeio pela Icefields Parkway', 'Parque Nacional de Jasper', 'Cânion Maligne & Lago', 'Retorno a Calgary & Partida'], imageUrl: 'https://picsum.photos/seed/canadapkg/600/400', details: 'Embarque em uma jornada inesquecível pelas deslumbrantes paisagens das Rochosas Canadenses.'},
];

export const INITIAL_BLOG_POSTS_DATA: BlogPost[] = [
  { id: 'blog1', title: 'Top 10 Coisas para Fazer no Porto', author: 'Equipe Ubuntu Travel', date: '2024-07-15', excerpt: 'Descubra as melhores atrações, comidas e experiências na vibrante segunda cidade de Portugal...', imageUrl: 'https://picsum.photos/seed/porto/600/400', content: 'Conteúdo completo sobre o Porto...' },
  { id: 'blog2', title: 'Guia para Navegar no Metrô de Londres', author: 'Joana Silva', date: '2024-07-10', excerpt: 'Dicas e truques para dominar o extenso sistema de metrô de Londres como um local...', imageUrl: 'https://picsum.photos/seed/londonunderground/600/400', content: 'Conteúdo completo sobre o Metrô de Londres...' },
  { id: 'blog3', title: 'Explorando a Cena Culinária de Montreal', author: 'Equipe Ubuntu Travel', date: '2024-06-28', excerpt: 'De poutine a bagels, mergulhe nos diversos sabores de Montreal.', imageUrl: 'https://picsum.photos/seed/montrealfood/600/400', content: 'Conteúdo completo sobre a comida de Montreal...' },
];
